import SK21 from './productsImg/sk2-1.jpeg'
import SK22 from './productsImg/sk2-2.jpeg'
import SK23 from './productsImg/sk2-3.jpeg'
import SK24 from './productsImg/sk2-4.jpeg'
import SK25 from './productsImg/sk2-5.jpeg'
import SK26 from './productsImg/sk2-6.jpeg'
import SK27 from './productsImg/sk2-7.jpeg'
import HABA1 from './productsImg/haba-1.jpeg'
import HABA2 from './productsImg/haba-2.jpeg'
import HABA3 from './productsImg/haba-3.jpeg'
import HABA4 from './productsImg/haba-4.jpeg'
import HABA5 from './productsImg/haba-5.jpeg'
import HABA6 from './productsImg/haba-6.jpeg'
import SHISEIDO1 from './productsImg/shiseido-1.jpeg'
import SHISEIDO2 from './productsImg/shiseido-2.jpeg'
import SHISEIDO3 from './productsImg/shiseido-3.jpeg'
import SHISEIDO4 from './productsImg/shiseido-4.jpeg'
import SHISEIDO5 from './productsImg/shiseido-5.jpeg'
import YUEWEI1 from './productsImg/yuewei-1.jpeg'
import YUEWEI2 from './productsImg/yuewei-2.jpeg'
import YUEWEI3 from './productsImg/yuewei-3.jpeg'
import ELIXIR1 from './productsImg/elixir-1.jpeg'
import ELIXIR2 from './productsImg/elixir-2.jpeg'
import CPB1 from './productsImg/cpb-1.jpeg'
import FREEPLUS1 from './productsImg/freeplus-1.jpeg'
import DECORTE1 from './productsImg/decorte-1.jpeg'
import DECORTE2 from './productsImg/decorte-2.jpeg'
import CUREL1 from './productsImg/curel-1.jpeg'
import LAMER1 from './productsImg/lamer-1.jpeg'
import TF1 from './productsImg/tf-1.jpeg'
import YSL1 from './productsImg/ysl1.jpeg'
import PIGEON1 from './productsImg/pigeon1.jpeg'
import PIGEON2 from './productsImg/pigeon2.jpeg'
import PIGEON3 from './productsImg/pigeon3.jpeg'
import MAMAKID1 from './productsImg/mamakid1.jpeg'
import MAMAKID2 from './productsImg/mamakid2.jpeg'
import MAMAKID3 from './productsImg/mamakid3.jpeg'
import COMBI from './productsImg/combi.jpeg'
import DAMU from './productsImg/damu1.jpeg'
import KAWAI1 from './productsImg/kawai1.jpeg'
import KAWAI2 from './productsImg/kawai2.jpeg'
import DAZHENG from './productsImg/dazheng.jpeg'
import EVE1 from './productsImg/eve1.jpeg'
import EVE2 from './productsImg/eve2.jpeg'
import EVE3 from './productsImg/eve3.jpeg'
import KOWA from './productsImg/kowa1.jpeg'
import TAITIAN from './productsImg/taitian1.jpeg'
import LABA from './productsImg/laba1.jpeg'
import JIUXIN from './productsImg/jiuxin.jpeg'
import FX1 from './productsImg/fx-1.jpeg'
import FX2 from './productsImg/fx-2.jpeg'
import WUBIDI1 from './productsImg/wubidi-1.jpeg'
import WUBIDI2 from './productsImg/wubidi-2.jpeg'
import SANZAI1 from './productsImg/sanzai1.jpeg'
import SANZAI2 from './productsImg/sanzai2.jpeg'
import SANZAI3 from './productsImg/sanzai3.jpeg'
import ZUMALONG from './productsImg/zumalong.jpeg'

export const Products = [
  {
    id: 1,
    name: 'sk2面霜',
    size: '50g',
    price: 835,
    proImage: SK21,
  },
  {
    id: 2,
    name: 'sk2面霜',
    size: '80g',
    price: 1180,
    proImage: SK21,
  },
  {
    id: 3,
    name: 'sk2神仙水',
    size: '230ml',
    price: 1050,
    proImage: SK22,
  },
  {
    id: 4,
    name: 'sk2神仙水',
    size: '160ml',
    price: 820,
    proImage: SK22,
  },
  {
    id: 5,
    name: 'sk2洗脸奶',
    size: '120g',
    price: 348,
    proImage: SK23,
  },
  {
    id: 6,
    name: 'sk2福袋',
    size: '1组合',
    price: 1480,
    proImage: SK24,
  },
  {
    id: 7,
    name: 'sk2高保湿洗面奶',
    size: '50ml',
    price: 1520,
    proImage: SK25,
  },
  {
    id: 29,
    name: 'sk2美白小灯泡',
    size: '50ml',
    price: 1480,
    proImage: SK26,
  },
  {
    id: 32,
    name: 'sk2前男友面膜',
    size: '6片',
    price: 660,
    proImage: SK27,
  },
  {
    id: 8,
    name: 'haba-G露',
    size: '360ml',
    price: 280,
    proImage: HABA1,
  },
  {
    id: 9,
    name: 'haba-VC水',
    size: '180ml',
    price: 225,
    proImage: HABA2,
  },
  {
    id: 10,
    name: 'haba化妆水',
    size: '180ml',
    price: 148,
    proImage: HABA3,
  },
  {
    id: 11,
    name: 'haba角鲨烷油植物一代',
    size: '30ml',
    price: 180,
    proImage: HABA4,
  },
  {
    id: 12,
    name: 'haba角鲨烷油植物二代',
    size: '30ml',
    price: 170,
    proImage: HABA5,
  },
  {
    id: 13,
    name: 'haba角鲨烷油植物VC',
    size: '30ml',
    price: 180,
    proImage: HABA6,
  },
  {
    id: 14,
    name: 'shiseido资生堂百优面霜',
    size: '50g',
    price: 490,
    proImage: SHISEIDO1,
  },
  {
    id: 15,
    name: 'shiseido时光琉璃洗面奶',
    size: '134g',
    price: 332,
    proImage: SHISEIDO2,
  },
  {
    id: 16,
    name: 'shiseido资生堂红腰子精华',
    size: '50ml',
    price: 780,
    proImage: SHISEIDO3,
  },
  {
    id: 17,
    name: 'shiseido资生堂A醇眼霜',
    size: '20ml',
    price: 780,
    proImage: SHISEIDO4,
  },
  {
    id: 18,
    name: 'shiseido悦薇眼膜',
    size: '12包',
    price: 380,
    proImage: YUEWEI1,
  },
  {
    id: 19,
    name: 'shiseido悦薇眼霜',
    size: '15g',
    price: 580,
    proImage: YUEWEI2,
  },
  {
    id: 20,
    name: 'shiseido悦薇颈霜',
    size: '75g',
    price: 338,
    proImage: YUEWEI3,
  },
  {
    id: 30,
    name: 'shiseidoMAQuillAGE粉饼',
    size: '1盒',
    price: 288,
    proImage: SHISEIDO5,
  },
  {
    id: 21,
    name: 'ELIXIR抗皱精华霜',
    size: '22g',
    price: 450,
    proImage: ELIXIR1,
  },
  {
    id: 22,
    name: 'ELIXIR新品抗衰老化妆水',
    size: '170ml',
    price: 248,
    proImage: ELIXIR2,
  },
  {
    id: 23,
    name: 'CPB洗脸奶',
    size: '125g',
    price: 338,
    proImage: CPB1,
  },
  {
    id: 24,
    name: '芙丽芳丝洗脸奶',
    size: '100g',
    price: 140,
    proImage: FREEPLUS1,
  },
  {
    id: 25,
    name: '黛珂多重防晒隔离霜',
    size: '35g',
    price: 205,
    proImage: DECORTE1,
  },
  {
    id: 26,
    name: '黛珂多重防晒隔离霜',
    size: '60g',
    price: 270,
    proImage: DECORTE2,
  },
  {
    id: 27,
    name: '珂润面霜',
    size: '40g',
    price: 158,
    proImage: CUREL1,
  },
  {
    id: 28,
    name: '海蓝之谜洗脸奶',
    size: '125g',
    price: 778,
    proImage: LAMER1,
  },
  {
    id: 29,
    name: 'TomFord各色号口红',
    size: '1支',
    price: 415,
    proImage: TF1,
  },
  {
    id: 36,
    name: 'YSL黑/粉气垫粉底',
    size: '1盒',
    price: 520,
    proImage: YSL1,
  },
  {
    id: 30,
    name: '贝亲奶瓶玻璃',
    size: '1个',
    price: 145,
    proImage: PIGEON1,
  },
  {
    id: 31,
    name: '贝亲奶瓶塑料',
    size: '1个',
    price: 150,
    proImage: PIGEON2,
  },
  {
    id: 41,
    name: '贝亲桃子水',
    size: '200ml',
    price: 89,
    proImage: PIGEON3,
  },
  {
    id: 33,
    name: 'mamakids口水膏',
    size: '1支',
    price: 128,
    proImage: MAMAKID1,
  },
  {
    id: 34,
    name: 'mamakids面霜',
    size: '1支',
    price: 128,
    proImage: MAMAKID2,
  },
  {
    id: 35,
    name: 'mamakids身体乳',
    size: '310g',
    price: 385,
    proImage: MAMAKID3,
  },
  {
    id: 37,
    name: 'combi辅食杯',
    size: '1个',
    price: 128,
    proImage: COMBI,
  },
  {
    id: 38,
    name: '大木维生素软糖',
    size: '120粒',
    price: 168,
    proImage: DAMU,
  },
  {
    id: 39,
    name: 'kawai鱼肝油黄罐',
    size: '300粒',
    price: 198,
    proImage: KAWAI1,
  },
  {
    id: 40,
    name: 'kawai鱼肝油蓝罐',
    size: '180粒',
    price: 195,
    proImage: KAWAI2,
  },
  {
    id: 42,
    name: '大正感冒药',
    size: '44包',
    price: 120,
    proImage: DAZHENG,
  },
  {
    id: 43,
    name: 'EVE退热止痛蓝色',
    size: '40片',
    price: 120,
    proImage: EVE1,
  },
  {
    id: 44,
    name: 'EVE生理止痛粉色',
    size: '40片',
    price: 100,
    proImage: EVE2,
  },
  {
    id: 45,
    name: 'EVE退热止痛白色',
    size: '60片',
    price: 88,
    proImage: EVE3,
  },
  {
    id: 46,
    name: 'kowa肠胃药',
    size: '200粒',
    price: 155,
    proImage: KOWA,
  },
  {
    id: 47,
    name: '太田胃散',
    size: '48包',
    price: 105,
    proImage: TAITIAN,
  },
  {
    id: 48,
    name: '喇叭正露丸',
    size: '100粒',
    price: 85,
    proImage: LABA,
  },
  {
    id: 49,
    name: '救心丸',
    size: '60粒',
    price: 250,
    proImage: JIUXIN,
  },
  {
    id: 50,
    name: '救心丸',
    size: '120粒',
    price: 450,
    proImage: JIUXIN,
  },
  {
    id: 51,
    name: '救心丸',
    size: '310粒',
    price: 965,
    proImage: JIUXIN,
  },
  {
    id: 52,
    name: 'fx眼药水金色',
    size: '1瓶',
    price: 59,
    proImage: FX1,
  },
  {
    id: 53,
    name: 'fx眼药水印色',
    size: '1瓶',
    price: 38,
    proImage: FX2,
  },
  {
    id: 54,
    name: '无比滴普通版',
    size: '60g',
    price: 42,
    proImage: WUBIDI1,
  },
  {
    id: 55,
    name: '无比滴儿童版',
    size: '80g',
    price: 68,
    proImage: WUBIDI2,
  },
  {
    id: 56,
    name: '三宅一生1',
    size: '1个',
    price: 4000,
    proImage: SANZAI1,
  },
  {
    id: 57,
    name: '三宅一生2',
    size: '1个',
    price: 4000,
    proImage: SANZAI2,
  },
  {
    id: 58,
    name: '三宅一生2',
    size: '1个',
    price: 4000,
    proImage: SANZAI3,
  },
  {
    id: 59,
    name: '祖马龙香水',
    size: '1瓶',
    price: 450,
    proImage: ZUMALONG,
  },
]
export const MakeupProducts = [
  {
    id: 1,
    name: 'sk2面霜',
    size: '50g',
    price: 835,
    proImage: SK21,
  },
  {
    id: 2,
    name: 'sk2面霜',
    size: '80g',
    price: 1180,
    proImage: SK21,
  },
  {
    id: 3,
    name: 'sk2神仙水',
    size: '230ml',
    price: 1050,
    proImage: SK22,
  },
  {
    id: 4,
    name: 'sk2神仙水',
    size: '160ml',
    price: 820,
    proImage: SK22,
  },
  {
    id: 5,
    name: 'sk2洗脸奶',
    size: '120g',
    price: 348,
    proImage: SK23,
  },
  {
    id: 6,
    name: 'sk2福袋',
    size: '1组合',
    price: 1480,
    proImage: SK24,
  },
  {
    id: 7,
    name: 'sk2高保湿洗面奶',
    size: '50ml',
    price: 1520,
    proImage: SK25,
  },
  {
    id: 29,
    name: 'sk2美白小灯泡',
    size: '50ml',
    price: 1480,
    proImage: SK26,
  },
  {
    id: 32,
    name: 'sk2前男友面膜',
    size: '6片',
    price: 660,
    proImage: SK27,
  },
  {
    id: 8,
    name: 'haba-G露',
    size: '360ml',
    price: 280,
    proImage: HABA1,
  },
  {
    id: 9,
    name: 'haba-VC水',
    size: '180ml',
    price: 225,
    proImage: HABA2,
  },
  {
    id: 10,
    name: 'haba化妆水',
    size: '180ml',
    price: 148,
    proImage: HABA3,
  },
  {
    id: 11,
    name: 'haba角鲨烷油植物一代',
    size: '30ml',
    price: 180,
    proImage: HABA4,
  },
  {
    id: 12,
    name: 'haba角鲨烷油植物二代',
    size: '30ml',
    price: 170,
    proImage: HABA5,
  },
  {
    id: 13,
    name: 'haba角鲨烷油植物VC',
    size: '30ml',
    price: 180,
    proImage: HABA6,
  },
  {
    id: 14,
    name: 'shiseido资生堂百优面霜',
    size: '50g',
    price: 490,
    proImage: SHISEIDO1,
  },
  {
    id: 15,
    name: 'shiseido时光琉璃洗面奶',
    size: '134g',
    price: 332,
    proImage: SHISEIDO2,
  },
  {
    id: 16,
    name: 'shiseido资生堂红腰子精华',
    size: '50ml',
    price: 780,
    proImage: SHISEIDO3,
  },
  {
    id: 17,
    name: 'shiseido资生堂A醇眼霜',
    size: '20ml',
    price: 780,
    proImage: SHISEIDO4,
  },
  {
    id: 18,
    name: 'shiseido悦薇眼膜',
    size: '12包',
    price: 380,
    proImage: YUEWEI1,
  },
  {
    id: 19,
    name: 'shiseido悦薇眼霜',
    size: '15g',
    price: 580,
    proImage: YUEWEI2,
  },
  {
    id: 20,
    name: 'shiseido悦薇颈霜',
    size: '75g',
    price: 338,
    proImage: YUEWEI3,
  },
  {
    id: 30,
    name: 'shiseidoMAQuillAGE粉饼',
    size: '1盒',
    price: 288,
    proImage: SHISEIDO5,
  },
  {
    id: 21,
    name: 'ELIXIR抗皱精华霜',
    size: '22g',
    price: 450,
    proImage: ELIXIR1,
  },
  {
    id: 22,
    name: 'ELIXIR新品抗衰老化妆水',
    size: '170ml',
    price: 248,
    proImage: ELIXIR2,
  },
  {
    id: 23,
    name: 'CPB洗脸奶',
    size: '125g',
    price: 338,
    proImage: CPB1,
  },
  {
    id: 24,
    name: '芙丽芳丝洗脸奶',
    size: '100g',
    price: 140,
    proImage: FREEPLUS1,
  },
  {
    id: 25,
    name: '黛珂多重防晒隔离霜',
    size: '35g',
    price: 205,
    proImage: DECORTE1,
  },
  {
    id: 26,
    name: '黛珂多重防晒隔离霜',
    size: '60g',
    price: 270,
    proImage: DECORTE2,
  },
  {
    id: 27,
    name: '珂润面霜',
    size: '40g',
    price: 158,
    proImage: CUREL1,
  },
  {
    id: 28,
    name: '海蓝之谜洗脸奶',
    size: '125g',
    price: 778,
    proImage: LAMER1,
  },
  {
    id: 29,
    name: 'TomFord各色号口红',
    size: '1支',
    price: 415,
    proImage: TF1,
  },
  {
    id: 36,
    name: 'YSL黑/粉气垫粉底',
    size: '1盒',
    price: 520,
    proImage: YSL1,
  },
]

export const MedicineProducts = [
  {
    id: 38,
    name: '大木维生素软糖',
    size: '120粒',
    price: 168,
    proImage: DAMU,
  },
  {
    id: 39,
    name: 'kawai鱼肝油黄罐',
    size: '300粒',
    price: 198,
    proImage: KAWAI1,
  },
  {
    id: 40,
    name: 'kawai鱼肝油蓝罐',
    size: '180粒',
    price: 195,
    proImage: KAWAI2,
  },
  {
    id: 42,
    name: '大正感冒药',
    size: '44包',
    price: 120,
    proImage: DAZHENG,
  },
  {
    id: 43,
    name: 'EVE退热止痛蓝色',
    size: '40片',
    price: 120,
    proImage: EVE1,
  },
  {
    id: 44,
    name: 'EVE生理止痛粉色',
    size: '40片',
    price: 100,
    proImage: EVE2,
  },
  {
    id: 45,
    name: 'EVE退热止痛白色',
    size: '60片',
    price: 88,
    proImage: EVE3,
  },
  {
    id: 46,
    name: 'kowa肠胃药',
    size: '200粒',
    price: 155,
    proImage: KOWA,
  },
  {
    id: 47,
    name: '太田胃散',
    size: '48包',
    price: 105,
    proImage: TAITIAN,
  },
  {
    id: 48,
    name: '喇叭正露丸',
    size: '100粒',
    price: 85,
    proImage: LABA,
  },
  {
    id: 49,
    name: '救心丸',
    size: '60粒',
    price: 250,
    proImage: JIUXIN,
  },
  {
    id: 50,
    name: '救心丸',
    size: '120粒',
    price: 450,
    proImage: JIUXIN,
  },
  {
    id: 51,
    name: '救心丸',
    size: '310粒',
    price: 965,
    proImage: JIUXIN,
  },
  {
    id: 52,
    name: 'fx眼药水金色',
    size: '1瓶',
    price: 59,
    proImage: FX1,
  },
  {
    id: 53,
    name: 'fx眼药水印色',
    size: '1瓶',
    price: 38,
    proImage: FX2,
  },
  {
    id: 54,
    name: '无比滴普通版',
    size: '60g',
    price: 42,
    proImage: WUBIDI1,
  },
  {
    id: 55,
    name: '无比滴儿童版',
    size: '80g',
    price: 68,
    proImage: WUBIDI2,
  },
]
export const MakeupOthers = [
  {
    id: 21,
    name: 'ELIXIR抗皱精华霜',
    size: '22g',
    price: 450,
    proImage: ELIXIR1,
  },
  {
    id: 22,
    name: 'ELIXIR新品抗衰老化妆水',
    size: '170ml',
    price: 248,
    proImage: ELIXIR2,
  },
  {
    id: 23,
    name: 'CPB洗脸奶',
    size: '125g',
    price: 338,
    proImage: CPB1,
  },
  {
    id: 24,
    name: '芙丽芳丝洗脸奶',
    size: '100g',
    price: 140,
    proImage: FREEPLUS1,
  },
  {
    id: 25,
    name: '黛珂多重防晒隔离霜',
    size: '35g',
    price: 205,
    proImage: DECORTE1,
  },
  {
    id: 26,
    name: '黛珂多重防晒隔离霜',
    size: '60g',
    price: 270,
    proImage: DECORTE2,
  },
  {
    id: 27,
    name: '珂润面霜',
    size: '40g',
    price: 158,
    proImage: CUREL1,
  },
  {
    id: 28,
    name: '海蓝之谜洗脸奶',
    size: '125g',
    price: 778,
    proImage: LAMER1,
  },
  {
    id: 29,
    name: 'TomFord各色号口红',
    size: '1支',
    price: 415,
    proImage: TF1,
  },
  {
    id: 36,
    name: 'YSL黑/粉气垫粉底',
    size: '1盒',
    price: 520,
    proImage: YSL1,
  },
]
export const Goodsale = [
  {
    id: 2,
    name: 'sk2面霜',
    size: '80g',
    price: 1180,
    proImage: SK21,
  },
  {
    id: 4,
    name: 'sk2神仙水',
    size: '160ml',
    price: 820,
    proImage: SK22,
  },
  {
    id: 8,
    name: 'haba-G露',
    size: '360ml',
    price: 280,
    proImage: HABA1,
  },
  {
    id: 11,
    name: 'haba角鲨烷油植物一代',
    size: '30ml',
    price: 180,
    proImage: HABA4,
  },
  {
    id: 12,
    name: 'haba角鲨烷油植物二代',
    size: '30ml',
    price: 170,
    proImage: HABA5,
  },
  {
    id: 49,
    name: '救心丸',
    size: '60粒',
    price: 250,
    proImage: JIUXIN,
  },
  {
    id: 43,
    name: 'EVE退热止痛蓝色',
    size: '40片',
    price: 120,
    proImage: EVE1,
  },
  {
    id: 44,
    name: 'EVE生理止痛粉色',
    size: '40片',
    price: 100,
    proImage: EVE2,
  },
  {
    id: 42,
    name: '大正感冒药',
    size: '44包',
    price: 120,
    proImage: DAZHENG,
  },
]
export const HABA = [
  {
    id: 8,
    name: 'haba-G露',
    size: '360ml',
    price: 280,
    proImage: HABA1,
  },
  {
    id: 9,
    name: 'haba-VC水',
    size: '180ml',
    price: 225,
    proImage: HABA2,
  },
  {
    id: 10,
    name: 'haba化妆水',
    size: '180ml',
    price: 148,
    proImage: HABA3,
  },
  {
    id: 11,
    name: 'haba角鲨烷油植物一代',
    size: '30ml',
    price: 180,
    proImage: HABA4,
  },
  {
    id: 12,
    name: 'haba角鲨烷油植物二代',
    size: '30ml',
    price: 170,
    proImage: HABA5,
  },
  {
    id: 13,
    name: 'haba角鲨烷油植物VC',
    size: '30ml',
    price: 180,
    proImage: HABA6,
  },
]
export const SK2 = [
  {
    id: 1,
    name: 'sk2面霜',
    size: '50g',
    price: 835,
    proImage: SK21,
  },
  {
    id: 2,
    name: 'sk2面霜',
    size: '80g',
    price: 1180,
    proImage: SK21,
  },
  {
    id: 3,
    name: 'sk2神仙水',
    size: '230ml',
    price: 1050,
    proImage: SK22,
  },
  {
    id: 4,
    name: 'sk2神仙水',
    size: '160ml',
    price: 820,
    proImage: SK22,
  },
  {
    id: 5,
    name: 'sk2洗脸奶',
    size: '120g',
    price: 348,
    proImage: SK23,
  },
  {
    id: 6,
    name: 'sk2福袋',
    size: '1组合',
    price: 1480,
    proImage: SK24,
  },
  {
    id: 7,
    name: 'sk2高保湿洗面奶',
    size: '50ml',
    price: 1520,
    proImage: SK25,
  },
  {
    id: 29,
    name: 'sk2美白小灯泡',
    size: '50ml',
    price: 1480,
    proImage: SK26,
  },
  {
    id: 32,
    name: 'sk2前男友面膜',
    size: '6片',
    price: 660,
    proImage: SK27,
  },
]
export const SHISEIDO = [
  {
    id: 14,
    name: 'shiseido资生堂百优面霜',
    size: '50g',
    price: 490,
    proImage: SHISEIDO1,
  },
  {
    id: 15,
    name: 'shiseido时光琉璃洗面奶',
    size: '134g',
    price: 332,
    proImage: SHISEIDO2,
  },
  {
    id: 16,
    name: 'shiseido资生堂红腰子精华',
    size: '50ml',
    price: 780,
    proImage: SHISEIDO3,
  },
  {
    id: 17,
    name: 'shiseido资生堂A醇眼霜',
    size: '20ml',
    price: 780,
    proImage: SHISEIDO4,
  },
  {
    id: 18,
    name: 'shiseido悦薇眼膜',
    size: '12包',
    price: 380,
    proImage: YUEWEI1,
  },
  {
    id: 19,
    name: 'shiseido悦薇眼霜',
    size: '15g',
    price: 580,
    proImage: YUEWEI2,
  },
  {
    id: 20,
    name: 'shiseido悦薇颈霜',
    size: '75g',
    price: 338,
    proImage: YUEWEI3,
  },
  {
    id: 30,
    name: 'shiseidoMAQuillAGE粉饼',
    size: '1盒',
    price: 288,
    proImage: SHISEIDO5,
  },
]
export const ProOthers = [
  {
    id: 56,
    name: '三宅一生1',
    size: '1个',
    price: 4000,
    proImage: SANZAI1,
  },
  {
    id: 57,
    name: '三宅一生2',
    size: '1个',
    price: 4000,
    proImage: SANZAI2,
  },
  {
    id: 58,
    name: '三宅一生2',
    size: '1个',
    price: 4000,
    proImage: SANZAI3,
  },
  {
    id: 59,
    name: '祖马龙香水',
    size: '1瓶',
    price: 450,
    proImage: ZUMALONG,
  },
]
export const ProBaby = [
  {
    id: 30,
    name: '贝亲奶瓶玻璃',
    size: '1个',
    price: 145,
    proImage: PIGEON1,
  },
  {
    id: 31,
    name: '贝亲奶瓶塑料',
    size: '1个',
    price: 150,
    proImage: PIGEON2,
  },
  {
    id: 41,
    name: '贝亲桃子水',
    size: '200ml',
    price: 89,
    proImage: PIGEON3,
  },
  {
    id: 33,
    name: 'mamakids口水膏',
    size: '1支',
    price: 128,
    proImage: MAMAKID1,
  },
  {
    id: 34,
    name: 'mamakids面霜',
    size: '1支',
    price: 128,
    proImage: MAMAKID2,
  },
  {
    id: 35,
    name: 'mamakids身体乳',
    size: '310g',
    price: 385,
    proImage: MAMAKID3,
  },
  {
    id: 37,
    name: 'combi辅食杯',
    size: '1个',
    price: 128,
    proImage: COMBI,
  },
  {
    id: 38,
    name: '大木维生素软糖',
    size: '120粒',
    price: 168,
    proImage: DAMU,
  },
  {
    id: 39,
    name: 'kawai鱼肝油黄罐',
    size: '300粒',
    price: 198,
    proImage: KAWAI1,
  },
  {
    id: 40,
    name: 'kawai鱼肝油蓝罐',
    size: '180粒',
    price: 195,
    proImage: KAWAI2,
  },
]
